sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "14"

branches:
  only:
    - demo

before_script:
  - npm install -g @angular/cli

script:
  - ng build --configuration=demo --localize
  - DIST=dist-demo npm run postbuild

deploy:
  provider: pages
  local-dir: dist-demo
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: demo
  repo: ArPIHomeSecurity/arpi_webapplication
  target_branch: gh-pages
  fqdn: demo.arpi-security.info