sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - demo

before_script:
  - npm install -g @angular/cli

script:
  - ng build --configuration=demo-en
  - ng build --configuration=demo-hu
  - cp dist-demo/index.html dist-demo/404.html
  - cp dist-demo/hu/index.html dist-demo/hu/404.html

deploy:
  provider: pages
  local-dir: dist-demo
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: demo
  repo: ArPIHomeSecurity/arpi_webapplication
  target_branch: gh-pages
  fqdn: demo.arpi-security.info
